version: '2'

services:
  slurmflowctld:
    container_name: slurmflowctld
    environment:
      SLURM_CLUSTER_NAME: ddhpc
      SLURM_CONTROL_MACHINE: slurmflowctld
      SLURM_NODE_NAMES: slurmflowd
      INFLUXDB_HOST: influxdb
      INFLUXDB_DATABASE_NAME: docker_slurm
    tty: true
    hostname: slurmflowctld
    networks:
      default:
        aliases:
          - slurmflowctld
    image: cbmckni/slurmflowctld
    stdin_open: true
  slurmflowd:
    container_name: slurmflowd
    environment:
      SLURM_CONTROL_MACHINE: slurmflowctld
      SLURM_CLUSTER_NAME: ddhpc
      SLURM_NODE_NAMES: slurmflowd
      INFLUXDB_HOST: influxdb
      INFLUXDB_DATABASE_NAME: docker_slurm
    tty: true
    hostname: slurmflowd
    networks:
      default:
        aliases:
          - slurmflowd
    image: cbmckni/slurmflowd
    depends_on:
      - slurmflowctld
    stdin_open: true
